In [10]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)
def norm_zeroone(x):
    n = x - np.min(x,0)
    d = np.max(x,0) - np.min(x,0)
    return n/(d+1e-7)
def norm_standard(x):
    n = x - np.mean(x)
    d = np.std(x)
    return n/d

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973], 
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007], 
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973], 
               [816, 820.958984, 1008100, 815.48999, 819.23999], 
               [819.359985, 823, 1188100, 818.469971, 818.97998], 
               [819, 823, 1198100, 816, 820.450012], 
               [811.700012, 815.25, 1098100, 809.780029, 813.669983], 
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy = norm_zeroone(xy)
print(xy)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None,1])
W = tf.Variable(tf.random_normal([4,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = tf.matmul(X,W)+b
cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train],feed_dict={X:x_data,Y:y_data})
    if(step%100==0):
        print(step,"Cost : ",cost_val,"Prediction : ",hy_val)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost :  0.386387 Prediction :  [[0.80469835]
 [0.6423676 ]
 [0.9283773 ]
 [1.1906192 ]
 [1.0728735 ]
 [0.87574637]
 [1.279675  ]
 [0.78469896]]
100 Cost :  0.38543785 Prediction :  [[0.80326784]
 [0.6408453 ]
 [0.9270431 ]
 [1.1894984 ]
 [1.0716277 ]
 [0.87452614]
 [1.2786683 ]
 [0.78367335]]
200 Cost :  0.38449204 Prediction :  [[0.8018373 ]
 [0.6393237 ]
 [0.9257095 ]
 [1.1883779 ]
 [1.0703825 ]
 [0.87330616]
 [1.2776617 ]
 [0.7826481 ]]
300 Cost :  0.3835499 Prediction :  [[0.8004068 ]
 [0.63780427]
 [0.9243771 ]
 [1.1872574